//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.29 at 02:32:39 PM UTC 
//


package personnel;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for HOME_ADDRESSType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="HOME_ADDRESSType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}STREET_AND_NR"/>
 *         &lt;element ref="{}ZIP_CODE"/>
 *         &lt;element ref="{}CITY"/>
 *         &lt;element ref="{}PHONE_PRIVATE"/>
 *         &lt;element ref="{}MOBILE"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "HOME_ADDRESSType", propOrder = {
    "streetandnr",
    "zipcode",
    "city",
    "phoneprivate",
    "mobile"
})
public class HOMEADDRESSType {

    @XmlElement(name = "STREET_AND_NR", required = true)
    protected String streetandnr;
    @XmlElement(name = "ZIP_CODE", required = true)
    protected String zipcode;
    @XmlElement(name = "CITY", required = true)
    protected String city;
    @XmlElement(name = "PHONE_PRIVATE", required = true)
    protected String phoneprivate;
    @XmlElement(name = "MOBILE", required = true)
    protected String mobile;

    /**
     * Gets the value of the streetandnr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSTREETANDNR() {
        return streetandnr;
    }

    /**
     * Sets the value of the streetandnr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSTREETANDNR(String value) {
        this.streetandnr = value;
    }

    /**
     * Gets the value of the zipcode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getZIPCODE() {
        return zipcode;
    }

    /**
     * Sets the value of the zipcode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setZIPCODE(String value) {
        this.zipcode = value;
    }

    /**
     * Gets the value of the city property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCITY() {
        return city;
    }

    /**
     * Sets the value of the city property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCITY(String value) {
        this.city = value;
    }

    /**
     * Gets the value of the phoneprivate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPHONEPRIVATE() {
        return phoneprivate;
    }

    /**
     * Sets the value of the phoneprivate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPHONEPRIVATE(String value) {
        this.phoneprivate = value;
    }

    /**
     * Gets the value of the mobile property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMOBILE() {
        return mobile;
    }

    /**
     * Sets the value of the mobile property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMOBILE(String value) {
        this.mobile = value;
    }

}
