//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.29 at 02:32:39 PM UTC 
//


package personnel;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the personnel package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _WORKPHONE1_QNAME = new QName("", "WORKPHONE1");
    private final static QName _WORKPHONE2_QNAME = new QName("", "WORKPHONE2");
    private final static QName _CITY_QNAME = new QName("", "CITY");
    private final static QName _ROOMNR_QNAME = new QName("", "ROOMNR");
    private final static QName _STREETANDNR_QNAME = new QName("", "STREET_AND_NR");
    private final static QName _ZIPCODE_QNAME = new QName("", "ZIP_CODE");
    private final static QName _PHONEPRIVATE_QNAME = new QName("", "PHONE_PRIVATE");
    private final static QName _LOGIN_QNAME = new QName("", "LOGIN");
    private final static QName _EMAILADDRESS_QNAME = new QName("", "E_MAIL_ADDRESS");
    private final static QName _FUNCTION_QNAME = new QName("", "FUNCTION");
    private final static QName _MOBILE_QNAME = new QName("", "MOBILE");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: personnel
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Personnel }
     * 
     */
    public Personnel createPersonnel() {
        return new Personnel();
    }

    /**
     * Create an instance of {@link PERSONType }
     * 
     */
    public PERSONType createPERSONType() {
        return new PERSONType();
    }

    /**
     * Create an instance of {@link HOMEADDRESSType }
     * 
     */
    public HOMEADDRESSType createHOMEADDRESSType() {
        return new HOMEADDRESSType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Short }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "WORKPHONE1")
    public JAXBElement<Short> createWORKPHONE1(Short value) {
        return new JAXBElement<Short>(_WORKPHONE1_QNAME, Short.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Short }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "WORKPHONE2")
    public JAXBElement<Short> createWORKPHONE2(Short value) {
        return new JAXBElement<Short>(_WORKPHONE2_QNAME, Short.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CITY")
    public JAXBElement<String> createCITY(String value) {
        return new JAXBElement<String>(_CITY_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ROOMNR")
    public JAXBElement<String> createROOMNR(String value) {
        return new JAXBElement<String>(_ROOMNR_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "STREET_AND_NR")
    public JAXBElement<String> createSTREETANDNR(String value) {
        return new JAXBElement<String>(_STREETANDNR_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ZIP_CODE")
    public JAXBElement<String> createZIPCODE(String value) {
        return new JAXBElement<String>(_ZIPCODE_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PHONE_PRIVATE")
    public JAXBElement<String> createPHONEPRIVATE(String value) {
        return new JAXBElement<String>(_PHONEPRIVATE_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "LOGIN")
    public JAXBElement<String> createLOGIN(String value) {
        return new JAXBElement<String>(_LOGIN_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "E_MAIL_ADDRESS")
    public JAXBElement<String> createEMAILADDRESS(String value) {
        return new JAXBElement<String>(_EMAILADDRESS_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "FUNCTION")
    public JAXBElement<String> createFUNCTION(String value) {
        return new JAXBElement<String>(_FUNCTION_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "MOBILE")
    public JAXBElement<String> createMOBILE(String value) {
        return new JAXBElement<String>(_MOBILE_QNAME, String.class, null, value);
    }

}
